version: '3'

volumes:
  pgdatasource:

services:
  db:
    image: postgres
    restart: always
    environment:
     - DATABASE_HOST=127.0.0.1
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=docker
     - POSTGRES_PORT=5432
     - POSTGRES_DB=dawnbreaker
    ports:
     - '5432:5432'
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
    volumes:
      - pgdatasource:/var/lib/postgresql/data

  server:
    build: dawnbreaker-dkp-backend/
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_PORT=5432
      - POSTGRES_DB=dawnbreaker
    volumes:
      - type: bind
        source: ./dawnbreaker-dkp-backend/
        target: /app
    command: npm start

  client:
    build: dawnbreaker-dkp-frontend/
    depends_on:
      - 'db'
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./dawnbreaker-dkp-frontend/src
        target: /app/src