version: '3'

volumes:
  pgdatasource:

services:
  db:
    image: postgres
    restart: always
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=docker
     - POSTGRES_PORT=5432
     - POSTGRES_DB=dawnbreaker
    ports:
     - '5432:5432'
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
    volumes:
      - pgdatasource:/var/lib/postgresql/data

  server:
    build: dawnbreaker-dkp-backend/
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=staging
      - CONNECTION=postgres://postgres:docker@db:5432/dawnbreaker
    volumes:
      - .:/src
    command: npm start

  client:
    build: dawnbreaker-dkp-frontend/
    depends_on:
      - db
    ports:
      - '80:80'
      - '3000:3000'
    environment:
      - API=http://localhost:8080
    volumes:
      - type: bind
        source: ./dawnbreaker-dkp-frontend/src
        target: /app/src

networks:
  local:
    driver: bridge


